target_to_label = {
    "12.1": "countries taking action on sustainable consumption and production",
    "12.2": "sustainable management and efficient use of natural resources",
    "12.3": "halve per capita global food waste and reduce food losses",
    "12.4": "environmentally sound management of all wastes",
    "12.5": "substantially reduce waste generation",
    "12.6": "encourage companies to integrate sustainability into their reporting cycle",
    "12.7": "promote public procurement practices that are sustainable",
    "12.8": "ensure that people have the relevant information and awareness for sustainable development and lifestyles",
    "12.a": "strengthen their scientific and technological capacity for sustainable patterns of consumption and production",
    "12.b": "sustainable tourism that creates jobs and promotes local culture and product",
    "12.c": "rationalizing inefficient fossil-fuel subsidies and wasteful consumption",
}

raw_target = {
    "12.1": "Implement the 10-year framework of programmes on sustainable consumption and production, all countries taking action, with developed countries taking the lead, taking into account the development and capabilities of developing countries",
    "12.2": "By 2030, achieve the sustainable management and efficient use of natural resources",
    "12.3": "By 2030, halve per capita global food waste at the retail and consumer levels and reduce food losses along production and supply chains, including post-harvest losses",
    "12.4": "By 2020, achieve the environmentally sound management of chemicals and all wastes throughout their life cycle, in accordance with agreed international frameworks, and significantly reduce their release to air, water and soil in order to minimize their adverse impacts on human health and the environment",
    "12.5": "By 2030, substantially reduce waste generation through prevention, reduction, recycling and reuse",
    "12.6": "Encourage companies, especially large and transnational companies, to adopt sustainable practices and to integrate sustainability information into their reporting cycle",
    "12.7": "Promote public procurement practices that are sustainable, in accordance with national policies and priorities",
    "12.8": "By 2030, ensure that people everywhere have the relevant information and awareness for sustainable development and lifestyles in harmony with nature",
    "12.a": "Support developing countries to strengthen their scientific and technological capacity to move towards more sustainable patterns of consumption and production",
    "12.b": "Develop and implement tools to monitor sustainable development impacts for sustainable tourism that creates jobs and promotes local culture and products",
    "12.c": "Rationalize inefficient fossil-fuel subsidies that encourage wasteful consumption by removing market distortions, in accordance with national circumstances, including by restructuring taxation and phasing out those harmful subsidies, where they exist, to reflect their environmental impacts, taking fully into account the specific needs and conditions of developing countries and minimizing the possible adverse impacts on their development in a manner that protects the poor and the affected communities",
    "15.1": "By 2020, ensure the conservation, restoration and sustainable use of terrestrial and inland freshwater ecosystems and their services, in particular forests, wetlands, mountains and drylands, in line with obligations under international agreements",
    "15.2": "By 2020, promote the implementation of sustainable management of all types of forests, halt deforestation, restore degraded forests and substantially increase afforestation and reforestation globally",
    "15.3": "By 2030, combat desertification, restore degraded land and soil, including land affected by desertification, drought and floods, and strive to achieve a land degradation-neutral world",
    "15.4": "By 2030, ensure the conservation of mountain ecosystems, including their biodiversity, in order to enhance their capacity to provide benefits that are essential for sustainable development",
    "15.5": "Take urgent and significant action to reduce the degradation of natural habitats, halt the loss of biodiversity and, by 2020, protect and prevent the extinction of threatened species",
    "15.6": "Promote fair and equitable sharing of the benefits arising from the utilization of genetic resources and promote appropriate access to such resources, as internationally agreed",
    "15.7": "Take urgent action to end poaching and trafficking of protected species of flora and fauna and address both demand and supply of illegal wildlife products",
    "15.8": "By 2020, introduce measures to prevent the introduction and significantly reduce the impact of invasive alien species on land and water ecosystems and control or eradicate the priority species",
    "15.9": "By 2020, integrate ecosystem and biodiversity values into national and local planning, development processes, poverty reduction strategies and accounts",
    "15.a": "Mobilize and significantly increase financial resources from all sources to conserve and sustainably use biodiversity and ecosystems",
    "15.b": "Mobilize significant resources from all sources and at all levels to finance sustainable forest management and provide adequate incentives to developing countries to advance such management, including for conservation and reforestation",
    "15.c": "Enhance global support for efforts to combat poaching and trafficking of protected species, including by increasing the capacity of local communities to pursue sustainable livelihood opportunities",
    "16.1": "Significantly reduce all forms of violence and related death rates everywhere",
    "16.2": "End abuse, exploitation, trafficking and all forms of violence against and torture of children",
    "16.3": "Promote the rule of law at the national and international levels and ensure equal access to justice for all",
    "16.4": "By 2030, significantly reduce illicit financial and arms flows, strengthen the recovery and return of stolen assets and combat all forms of organized crime",
    "16.5": "Substantially reduce corruption and bribery in all their forms",
    "16.6": "Develop effective, accountable and transparent institutions at all levels",
    "16.7": "Ensure responsive, inclusive, participatory and representative decision-making at all levels",
    "16.8": "Broaden and strengthen the participation of developing countries in the institutions of global governance",
    "16.9": "By 2030, provide legal identity for all, including birth registration",
    "16.10": "Ensure public access to information and protect fundamental freedoms, in accordance with national legislation and international agreements. Strengthen relevant national institutions, including through international cooperation, for building capacity at all levels, in particular in developing countries, to prevent violence and combat terrorism and crime",
    "16.b": "Promote and enforce non-discriminatory laws and policies for sustainable development",
}
